# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kadai08_ToDo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kadai08_ToDo
pod 'PKHUD', '~> 5.0'
use_frameworks!
target "ターゲット名"
pod 'TextFieldEffects'
post_install do |installer|
    installer.pods_project.targets.each do |target|
target.build_configurations.each do |configuration|
    configuration.build_settings['SWIFT_VERSION'] = "3.0"
end
    end

end
